// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/test/service.proto

package com.hyf.protobuf.test.service2;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:java.test.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string param = 1;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <code>string param = 1;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString
      getParamBytes();
}
