// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/test/service.proto

package com.hyf.protobuf.test.service2;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_java_test_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_java_test_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_java_test_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_java_test_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027java/test/service.proto\022\tjava.test\"\030\n\007" +
      "Request\022\r\n\005param\030\001 \001(\t\"3\n\010Response\022\014\n\004co" +
      "de\030\001 \001(\005\022\014\n\004text\030\002 \001(\t\022\013\n\003rtn\030\003 \001(\tB%\n\036c" +
      "om.hyf.protobuf.test.service2P\001\210\001\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_java_test_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_java_test_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_java_test_Request_descriptor,
        new java.lang.String[] { "Param", });
    internal_static_java_test_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_java_test_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_java_test_Response_descriptor,
        new java.lang.String[] { "Code", "Text", "Rtn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
