// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: java/test/address_book.proto

package com.hyf.protobuf.test;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:java.test.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .java.test.Person person = 1;</code>
   */
  java.util.List<com.hyf.protobuf.test.Person> 
      getPersonList();
  /**
   * <code>repeated .java.test.Person person = 1;</code>
   */
  com.hyf.protobuf.test.Person getPerson(int index);
  /**
   * <code>repeated .java.test.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .java.test.Person person = 1;</code>
   */
  java.util.List<? extends com.hyf.protobuf.test.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .java.test.Person person = 1;</code>
   */
  com.hyf.protobuf.test.PersonOrBuilder getPersonOrBuilder(
      int index);
}
