// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.hyf.protobuf.test.service;

/**
 * Protobuf service {@code java.test.MyService}
 */
public  abstract class MyService
    implements com.google.protobuf.Service {
  protected MyService() {}

  public interface Interface {
    /**
     * <code>rpc req(.java.test.Request) returns (.java.test.Response);</code>
     */
    public abstract void req(
        com.google.protobuf.RpcController controller,
        com.hyf.protobuf.test.service.Request request,
        com.google.protobuf.RpcCallback<com.hyf.protobuf.test.service.Response> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new MyService() {
      @java.lang.Override
      public  void req(
          com.google.protobuf.RpcController controller,
          com.hyf.protobuf.test.service.Request request,
          com.google.protobuf.RpcCallback<com.hyf.protobuf.test.service.Response> done) {
        impl.req(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.req(controller, (com.hyf.protobuf.test.service.Request)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.hyf.protobuf.test.service.Request.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.hyf.protobuf.test.service.Response.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc req(.java.test.Request) returns (.java.test.Response);</code>
   */
  public abstract void req(
      com.google.protobuf.RpcController controller,
      com.hyf.protobuf.test.service.Request request,
      com.google.protobuf.RpcCallback<com.hyf.protobuf.test.service.Response> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.hyf.protobuf.test.service.Service.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.req(controller, (com.hyf.protobuf.test.service.Request)request,
          com.google.protobuf.RpcUtil.<com.hyf.protobuf.test.service.Response>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.hyf.protobuf.test.service.Request.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.hyf.protobuf.test.service.Response.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.hyf.protobuf.test.service.MyService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void req(
        com.google.protobuf.RpcController controller,
        com.hyf.protobuf.test.service.Request request,
        com.google.protobuf.RpcCallback<com.hyf.protobuf.test.service.Response> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.hyf.protobuf.test.service.Response.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.hyf.protobuf.test.service.Response.class,
          com.hyf.protobuf.test.service.Response.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.hyf.protobuf.test.service.Response req(
        com.google.protobuf.RpcController controller,
        com.hyf.protobuf.test.service.Request request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.hyf.protobuf.test.service.Response req(
        com.google.protobuf.RpcController controller,
        com.hyf.protobuf.test.service.Request request)
        throws com.google.protobuf.ServiceException {
      return (com.hyf.protobuf.test.service.Response) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.hyf.protobuf.test.service.Response.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:java.test.MyService)
}

